# -*- coding: utf-8 -*-
{
    'name': 'Services',
    'version': '1.0',
    'category': 'Manufacturing',
    'summary': 'Service Order',
    'description': 'Service Order Repair',
    'depends': ['stock', 'sale_management', 'account', 'zaccount'],
    'data': [
        'security/service_security.xml',
        'security/ir.model.access.csv',
        'views/service_views.xml',
        'views/equipment_views.xml',
        # 'views/partner_views.xml',
        # 'data/ir_sequence_data.xml',
#         'data/product_category.xml',
        'report/service_reports.xml',
        'report/service_layout.xml',
        'report/service_template_service_order.xml',
        ],
    'images': [],
    'css': ['static/css/zstyle.css'],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
